import strawberry from './straw.webp'
import food1 from './food1.jpg'
import food2 from './food2.jpg'
import food3 from './food3.jpg'
import food4 from './food4.jpg'
import food5 from './food5.jpg'
import food6 from './food6.jpg'
import food7 from './food7.jpg'
import food8 from './food8.jpg'
import food9 from './food9.jpg'
import food10 from './food10.jpg'
import food11 from './food11.jpg'
import food12 from './food12.jpg'
import food13 from './food13.jpg'
import food14 from './food14.jpg'
import place1 from './place1.jpg'
import place2 from './place2.jpg'
import place3 from './place3.jpg'
import place4 from './place4.jpg'
import place5 from './place5.jpg'
import place6 from './place6.jpg'
import place7 from './place7.jpg'
import place8 from './place8.jpg'
import dog1 from './dog1.jpg'
import tree1 from './tree1.jpg'
import home1 from './home1.jpg'
import home2 from './home2.jpg'
import home3 from './home3.jpg'
import home4 from './home4.jpg'
import home5 from './home5.jpg'
import home6 from './home6.jpg'
import home7 from './home7.jpg'
import home8 from './home8.jpg'
import home9 from './home9.jpg'
import home10 from './home10.jpg'
import home11 from './home11.jpg'
import home12 from './home12.jpg'
import home13 from './home13.jpg'
import home14 from './home14.jpg'
import home15 from './home15.jpg'
import art1 from './art1.jpg'
import flower1 from './flower1.jpeg'
import flower2 from './flower2.jpeg'
import flower3 from './flower3.jpeg'
import flower4 from './flower4.jpeg'
import flower5 from './flower5.jpeg'
import night1 from './night1.jpg'
import night2 from './night2.jpg'
import night3 from './night3.jpg'
import night4 from './night4.jpg'
import night5 from './night5.jpg'
import night6 from './night6.jpg'
import night7 from './night7.jpg'
import night8 from './night8.jpg'
import night9 from './night9.jpg'
import night10 from './night10.jpg'
import night11 from './night11.jpg'
import night12 from './night12.jpg'
import night13 from './night13.jpg'
import night14 from './night14.jpg'
import pets1 from './pets1.jpg'
import pets2 from './pets2.jpg'
import pets3 from './pets3.jpg'
import pets4 from './pets4.jpg'
import pets5 from './pets5.jpg'
import pets6 from './pets6.jpg'
import pets7 from './pets7.jpg'
import pets8 from './pets8.jpg'
import pets9 from './pets9.jpg'
import pets10 from './pets10.jpg'
import pets11 from './pets11.jpg'
import pets12 from './pets12.jpg'
import pets13 from './pets13.jpg'
import pets14 from './pets14.jpg'

export default {strawberry,food1,food2,food3,food4,food5,food6,food7,food8,food9,food10,food11,food12,food13,food14,
place1,place2,place3,place4,place5,place6,place7,place8,
flower1,flower2,flower3,flower4,flower5,
dog1,tree1,art1,
home1,home2,home3,home4,home5,home6,home7,home8,home9,home10,home11,home12,home13,home14,home15,
night1,night2,night3,night4,night5,night6,night7,night8,night9,night10,night11,night12,night13,night14,
pets1,pets2,pets3,pets4,pets5,pets6,pets7,pets8,pets9,pets10,pets11,pets12,pets13,pets14}